source 'http://rubygems.org'

gem 'rails','3.2.11'

gem 'paperclip', '~>3.1.3'
gem 'delayed_paperclip'
gem 'haml'
gem 'twitter-bootstrap-rails'
gem 'devise'
gem 'aws-sdk'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'stripe'
gem 'truncate_html'
gem 'activerecord-postgresql-adapter'
gem 'oauth2'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-linkedin'
gem 'kaminari'
gem 'bitly'
gem 'filepicker-rails'
gem 'heroku'
gem 'therubyracer'
gem 'has_scope'
gem 'youtube_it'
gem 'rails_config'
gem 'easy_roles'
gem 'newrelic_rpm'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :production do
  gem 'pg'
  gem 'sass-rails',   '~> 3.2.3'
end

group :staging do
  gem 'pg'
  gem 'erb2haml'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'rails-dev-boost', :git => 'git://github.com/thedarkone/rails-dev-boost.git'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails_best_practices'
end

group :development, :test do
  gem 'pg'
  gem 'erb2haml'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'rails-dev-boost', :git => 'git://github.com/thedarkone/rails-dev-boost.git'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails_best_practices'
  # gem 'meta_request'
  # gem 'annotate'
  # gem 'bullet'
  gem 'debugger'
  # gem 'flay'
  # gem 'hirb'
  # gem 'lol_dba'
  # gem 'quiet_assets'
  # gem 'rack-mini-profiler'
  # gem 'rails-footnotes'
  # gem 'reek'
  # gem 'request-log-analyzer'
end

gem 'jquery-rails'
gem 'unicorn'
gem 'capistrano'
gem 'carrierwave'
gem 'mini_magick'
gem 'activemerchant', :require => 'active_merchant'
gem 'simple_form'
gem 'wicked'
gem 'validates_email_format_of'
gem 'merit'
#gem 'jquery-fileupload-rails'
#gem 'whenever', require: false
