development:
  bucket: venturebridge-dev
  access_key_id: AKIAIRG5XEIHBB42GFBQ
  secret_access_key: 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
test:
  bucket: venturebridge-dev
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
production:
  bucket: venturebridge
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']