development:
  bucket: venturebridge-dev
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
test:
  bucket: venturebridge-dev
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
production:
  bucket: venturebridge
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']